export const GOOGLE_MAILER_CLIENT_ID = process.env.GOOGLE_MAILER_CLIENT_ID;
export const GOOGLE_MAILER_CLIENT_SECRET =
  process.env.GOOGLE_MAILER_CLIENT_SECRET;
export const GOOGLE_MAILER_REFRESH_TOKEN =
  process.env.GOOGLE_MAILER_REFRESH_TOKEN;
export const ADMIN_EMAIL_ADDRESS = process.env.ADMIN_EMAIL_ADDRESS;
