import { Prisma } from '@prisma/client';

export const productVariantSeed: Prisma.ProductVariantsCreateManyInput[] = [
  {
    id: 1,
    productId: 1,
    price: 100,
    variant: 'Leg',
    quantity: 20,
  },
  {
    id: 2,
    productId: 1,
    price: 200,
    variant: 'Tenderloin',
    salePercent: 20,
    quantity: 60,
  },
  {
    id: 3,
    productId: 1,
    price: 400,
    variant: 'Chops',
    salePercent: 35,
    quantity: 30,
  },
  {
    id: 4,
    productId: 2,
    price: 20,
    variant: 'Normal',
    salePercent: 10,
    quantity: 500,
  },
  {
    id: 5,
    productId: 3,
    price: 50,
    variant: 'Normal',
    salePercent: 0,
    quantity: 200,
  },
  {
    id: 6,
    productId: 4,
    price: 50,
    variant: '1Kg',
    salePercent: 0,
    quantity: 100,
  },
  {
    id: 7,
    productId: 4,
    price: 90,
    variant: '2Kg',
    salePercent: 14,
    quantity: 100,
  },
  {
    id: 8,
    productId: 5,
    price: 300,
    variant: 'America',
    salePercent: 0,
    quantity: 100,
  },
  {
    id: 9,
    productId: 5,
    price: 180,
    variant: 'China',
    salePercent: 30,
    quantity: 300,
  },
  {
    id: 10,
    productId: 6,
    price: 10,
    variant: 'Small',
    salePercent: 0,
    quantity: 100,
  },
  {
    id: 11,
    productId: 6,
    price: 12,
    variant: 'Medium',
    salePercent: 0,
    quantity: 100,
  },
  {
    id: 12,
    productId: 6,
    price: 15,
    variant: 'Big',
    salePercent: 10,
    quantity: 100,
  },
  {
    id: 13,
    productId: 7,
    price: 40,
    variant: 'Normal',
    salePercent: 10,
    quantity: 200,
  },
  {
    id: 14,
    productId: 8,
    price: 25,
    variant: 'Normal',
    salePercent: 0,
    quantity: 400,
  },
];
